# Generated by Django 3.2.19 on 2023-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20230617_2250'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredients',
            name='unique_ingredients',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='units',
            new_name='measurement_unit',
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredients'),
        ),
    ]
