# Generated by Django 3.2.19 on 2023-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230607_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=10, verbose_name='Роль пользователя'),
        ),
    ]
